project_id="kunal-scratch"
cluster_name="gke-cluster-name"
region = "us-central1"
zones = "['us-central1-a']"
network = "default"
subnetwork = "bank-of-anthos-subnet-boa"
ip_range_pods = "pod-ips-secondary-range-boa"
ip_range_services = "svc-ips-secondary-range-boa"